language: java
jdk:
  - oraclejdk8
sudo: false
notifications:
  email:
    - recipients: klaudia.gluszek@gmail.com

before_script:
# get clone of GitHub repository to return Travis CI OW build/log files
# configure Git
 - git config --global user.email "michbodz@gmail.com"
 - git config --global user.name "michbodz"
 - git config --global push.default simple
   
after_failure:
## after failure transfer log files back to GitHub repository
 - cd $HOME/taxesUS
 - git checkout --quiet -f
## copy new log files to git repository tree
 - if [ ! -d bld ]; then mkdir bld; fi
 - cp $HOME/taxesUS/rel/bld/*.log bld/
 - if [ ! -d docs ]; then mkdir docs; fi
 - cp $HOME/taxesUS/docs/*.log docs/
## commit new log files to GitHub repository
 - git add -f .
 - git commit --quiet -m "Travis CI build $TRAVIS_BUILD_NUMBER (failure) - log files"
 - git push --quiet -f origin

after_success: |
  if [ -n "$GITHUB_OAUTH_TOKEN" ]; then
    cd "$TRAVIS_BUILD_DIR"
    mkdir web
    cp -r "$TRAVIS_BUILD_DIR" /web/
    cd web
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://<michbodz>:$GITHUB_OAUTH_TOKEN@github.com/<michbodz>/<taxexUS>-gh-pages gh-pages &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
  
deploy:
  edge: true
  provider: bluemixcloudfoundry
  username: klaudia.gluszek@gmail.com
  password:
    secure: gxdd1yL+J3DQHbppsaDqrOo8IoAAheDJDoVUoeS9RbtjI3wDq2HPx2KzEhg/wpwGwXGSkhCM6MklZWrecsfcp5B5nBQD7mnMiAzPwkmqULAskNVojFdaUEIRE7y72FpUQ9Tg7Sz5MeG4v4HWUK/hMzF3V65pz7HaqcVMqAAyf/fs8iAwaGbqsdNVpE+JicM+45Y5hYeUc7Do2XqBEgRSw23qrw9cF6oT79LyKVbF8aDeNRirMLEKRe78wKuO/xIS8Tt3QgwPTy3ekcQRhER186AUoYYaK8AepKfwseUn4GrJD747caoS1TcIi+pWlJxhqW+ucszef8u0DoBypbQIA7XKYOeONmVc/Qepx7k8r0TzFYZ9MW1r0ts5633ysTGd3IMCtWZV0n2ndMhgXIuVSivFoRTTWeS0ba2zgHr9KtP1tqzcCLFsnFpLb80Y0rABS7cKIbWDqmRpMRDV7+2AS1X8j1r541/j2tXz8BopGypI+glbKsniaO0P7mzx6LIoqhySLqHcAZc07un1ZEb3yFqrwxRDi4/flSbKXt8uTfgdpXecxFxEUR4pOUI8GugP3FIll1tARH+aIb8DBh5LUHI2JfOjXh41bcDK9uWrtYIp38ms9muNTvpa0cDYTL1heR2Cg+VNJqJjceRasq3C3kaobimrVYOSClx4BKdiYVg=
  organization: klaudia.gluszek
  space: dev
  manifest: manifest.yml          # (optional)  Defaults to manifest.yml.
  region: eu-gb                        # (optional)  [ng, eu-gb , au-syd] Defaults to US South region (ng).
  api: https://api.ng.bluemix.net
  
