language: java
jdk:
  - oraclejdk8
sudo: false
notifications:
  email:
    - recipients: klaudia.gluszek@gmail.com

before_script:
# get clone of GitHub repository to return Travis CI OW build/log files
# configure Git
 - git config --global user.email "michbodz@gmail.com"
 - git config --global user.name "michbodz"
 - git config --global push.default simple

after_failure:
## after failure transfer log files back to GitHub repository
 - cd $HOME/taxesUS
 - git checkout --quiet -f
## copy new log files to git repository tree
 - if [ ! -d bld ]; then mkdir bld; fi
 - cp $HOME/taxesUS/rel/bld/*.log bld/
 - if [ ! -d docs ]; then mkdir docs; fi
 - cp $HOME/taxesUS/docs/*.log docs/
## commit new log files to GitHub repository
 - git add -f .
 - git commit --quiet -m "Travis CI build $TRAVIS_BUILD_NUMBER (failure) - log files"
 - git push --quiet -f origin

after_success:
## after failure transfer log files back to GitHub repository
 - cd $HOME/taxesUS
 - git checkout --quiet -f
## copy new log files to git repository tree
 - if [ ! -d bld ]; then mkdir bld; fi
 - cp $HOME/michbodz/taxesUS/jobs/*.log bld/
 - if [ ! -d jobs ]; then mkdir jobs; fi
 - cp $HOME/michbodz/taxesUS/jobs/*.log jobs/
## commit new log files to GitHub repository
 - git add -f .
 - git commit --quiet -m "Travis CI build $TRAVIS_BUILD_NUMBER (failure) - log files"
 - git push --quiet -f origin

