language: java
jdk:
  - oraclejdk8
sudo: false
notifications:
  email:
    - recipients: klaudia.gluszek@gmail.com

after_success:
# after failure transfer log files back to GitHub repository
 - cd $home/travis/build/michbodz/taxesUS/src/test/resources
 - git checkout --quiet -f
# copy new log files to git repository tree
 - if [ ! -d bld ]; then mkdir bld; fi
 - cp $OWROOT/bld/*.log bld/
 - if [ ! -d docs ]; then mkdir docs; fi
 - cp $OWROOT/docs/*.log docs/
# commit new log files to GitHub repository
 - git add -f .
 - git commit --quiet -m "Travis CI build $TRAVIS_BUILD_NUMBER (failure) - log files"
 - git push --quiet -f origin

